# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: mrRob0to
email: mrRob0to@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
 xmr:47PZu2pUtrighJQUZj1JsaiHsM2wC4YRgiGtDQx
 nXQe5LPBEhpp1cvnN5DNrBZcpuoB6DG8CdjBhsMt
 PT7F62zWgCGUU1is
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mrRob0to.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mrRob0to

#SEO
defaults:
  - scope:
      path: ""
    values:
      image: /files/me2.png


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

header_pages:
  - whoami.md
  - links.md
  - posts.md

#Google Analytics
google_analytics: UA-54982866-5

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
